### ISSUE TITLE
export float data to json

### ISSUE THREAD

**Issue by landru29** [nilsmagnus/grib#1]
Here is my script to get wind data from NOAA
```
#!/bin/bash
DATE=`date +%Y%m%d`
echo "GET ${DATE}"
curl "http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_1p00.pl?file=gfs.t00z.pgrb2.1p00.f000&lev_10_m_above_ground=on&var_UGRD=on&var_VGRD=on&dir=%2Fgfs.${DATE}00" -o gfs.t00z.pgrb2.1p00.f000
```

With this command I get integers instead of floats
`./grib -file gfs.t00z.pgrb2.1p00.f000 -latMin -90000000 -latMax 90000000 -longMin 0 -longMax 359000000 -export 3`

**Comment by nilsmagnus** [comment]
If I understand http://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_temp5-3.shtml correct, the decimal scale factor in your case is 2, so all the numbers in the output can be divided by 100 to get the correct floatingpoint number for the datapoints. So the correct output should have been the current output divided by 100 (decimal scale of 2). Does this make sense @landru29 ?

**Comment by nilsmagnus** [comment]
Closing this, as it seems like the library is parsing correctly.
