### ISSUE TITLE
Eror while parsing data3

### ISSUE THREAD

**Issue by landru29** [nilsmagnus/grib#13]
data3 is not parsed correctly

You can check with : http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_1p00.pl?bottomlat=-90&dir=%2Fgfs.2019010612&file=gfs.t12z.pgrb2.1p00.f006&leftlon=0&lev_10_m_above_ground=on&rightlon=360&toplat=90&var_UGRD=on&var_VGRD=on

on the second message, data should be:
-1.09462
-1.03462
-0.964617
-0.904617
-0.834617
-0.774617
-0.714617
-0.644617
-0.574617
-0.514617
-0.444617

But I get:
-1.094617
-1.034617
14.255383
14.235383
14.255383
14.235383
14.245383
14.255383
14.245383
14.235383
14.255383

**Comment by landru29** [comment]
Can you tell me where you found the detail algo for  "complex packing and spacial differenting" ?

**Comment by landru29** [comment]
Can you tell me where you found the detail algo for  "complex packing and spacial differenting" ?

**Comment by nilsmagnus** [comment]
The algorithm is inspired by the wgrib2 library at https://ftp.cpc.ncep.noaa.gov/wd51we/wgrib2/ . It is written in fortran if I remember correctly.

**Comment by landru29** [comment]
It seems that it is the "spatial differencing" that is not correctly implemented.
I've used your code to implement data2 ("complex packing") and it works well
data3 is data2 + "spatial differencing" (see https://github.com/landru29/grib/blob/data2/griblib/data2.go)

**Comment by nilsmagnus** [comment]
Ok, I will try to see if I can find the bug(s) here. Feel free to have a look if you have time as well :)

**Comment by landru29** [comment]
should be fixed with my pull request: https://github.com/nilsmagnus/grib/pull/14

**Comment by nilsmagnus** [comment]
Indeed. Thanks! Did you look at the wgrib2 implementation to fix this, or how did you resolve it?

**Comment by landru29** [comment]
Yes, I used the old method that consists in putting some printf in c code and fmt.Printf in go code ;-)
