### ISSUE TITLE
Unexpected grid0 message length

### ISSUE THREAD

**Issue by measuredweighed** [nilsmagnus/grib#19]
I'm attempting to decode the [attached grib file](https://github.com/nilsmagnus/grib/files/4200883/gfs.t12z.pgrb2.0p25.f008-snow-depth.grib.zip), which is grid0 with an `Ni` = 1440 and `Nj` = 721. I've dealt with similar grib files using griblib in the past, but I'm seeing this particular file return a single message with a `Section7.Data` length of 468056 where I would typically expect 1038240 (`Ni * Nj`).

I've opened the grib file with an independent viewer and the data is listed there as expected (`Grid: 1440x721=1038240 points`). I've also confirmed that the `Section5.DataTemplateNumber` is 3, which I would expect.

Is this a decoding issue, or some grib peculiarity that I'm missing?

**Comment by measuredweighed** [comment]
I dug into this a little more using `wgrib2`. It appears the packing is listed as `c3b` which [this document](https://www.cpc.ncep.noaa.gov/products/wesley/wgrib2/set_grib_type.html) claims means `complex3-bitmap`:

```
wgrib2 gfs.t00z.pgrb2.0p25.f006-snow-depth.grib -packing
1:0:packing=grid point data - complex packing and spatial differencing,c3b
```

Indeed, when querying the file it claims to have bitmap data:
```
wgrib2 gfs.t00z.pgrb2.0p25.f006-snow-depth.grib -bitmap
1:0:bitmap 570473 undef pts
```

So a follow-up question: is griblib simply returning a `float64[]` of the encoded bitmap data, or is it handling the decoding? I'd expect the library to throw an error here if it's the former.

**Comment by nilsmagnus** [comment]
No worries, glad you figured it out.
