### ISSUE TITLE
grib2influx panics  with out of range

### ISSUE THREAD

**Issue by nilsmagnus** [nilsmagnus/grib#4]
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/nilsmagnus/grib/griblib.ParseData3(0x848a20, 0xc42908a060, 0x22eb, 0xc42004d080, 0x5, 0xc42d3c1438, 0x7000022f0)
	/home/larsgard/go/src/github.com/nilsmagnus/grib/griblib/data.go:215 +0x10fd
github.com/nilsmagnus/grib/griblib.ReadSection7(0x848a20, 0xc42908a060, 0x22eb, 0x40000000, 0x6258d19a01010004, 0x6deffffffff, 0x100000300, 0x6a00000001, 0x10208, 0x0, ...)
	/home/larsgard/go/src/github.com/nilsmagnus/grib/griblib/sections.go:341 +0x4d
github.com/nilsmagnus/grib/griblib.readMessage(0x848a20, 0xc42908a060, 0x202000047524942, 0x23ba, 0x202000047524942, 0x23ba, 0x1010200000007, 0xc0b0c07e1, 0x100, 0x0, ...)
	/home/larsgard/go/src/github.com/nilsmagnus/grib/griblib/sections.go:117 +0x537
github.com/nilsmagnus/grib/griblib.ReadMessage(0x849720, 0xc42000e040, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/larsgard/go/src/github.com/nilsmagnus/grib/griblib/sections.go:86 +0x2d9
github.com/nilsmagnus/grib/griblib.ReadMessages(0x849720, 0xc42000e040, 0x0, 0x0, 0x0, 0x1f96, 0x7ffdf9daecfc)
	/home/larsgard/go/src/github.com/nilsmagnus/grib/griblib/sections.go:51 +0xa9
main.main()
	/home/larsgard/go/src/github.com/nilsmagnus/grib2influx/main.go:47 +0x17a

**Comment by nilsmagnus** [comment]
Seems to be happening consistenly with 0-hour offset forecasts,
```

insert http---www.ftp.ncep.noaa.gov-data-nccf-com-gfs-prod-gfs.2017122206-gfs.t06z.pgrb2.1p00.f000
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/nilsmagnus/grib/griblib.ParseData3(0x848a20, 0xc427e08000, 0x232c, 0xc42004d080, 0x5, 0xc42dd48478, 0x700002331)
        /home/larsgard/go/src/github.com/nilsmagnus/grib/griblib/data.go:215 +0x10fd
github.com/nilsmagnus/grib/griblib.ReadSection7(0x848a20, 0xc427e08000, 0x232c, 0x40000000, 0x6258d19a01010004, 0x6c8ffffffff, 0x100000300, 0x6a00000001, 0x10208, 0x0, ...)
        /home/larsgard/go/src/github.com/nilsmagnus/grib/griblib/sections.go:341 +0x4d
github.com/nilsmagnus/grib/griblib.readMessage(0x848a20, 0xc427e08000, 0x202000047524942, 0x23fb, 0x202000047524942, 0x23fb, 0x1010200000007, 0x6160c07e1, 0x100, 0x0, ...)
        /home/larsgard/go/src/github.com/nilsmagnus/grib/griblib/sections.go:117 +0x537
github.com/nilsmagnus/grib/griblib.ReadMessage(0x849720, 0xc42000e040, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/larsgard/go/src/github.com/nilsmagnus/grib/griblib/sections.go:86 +0x2d9
github.com/nilsmagnus/grib/griblib.ReadMessages(0x849720, 0xc42000e040, 0x0, 0x0, 0x0, 0x1f96, 0x7fff41b11dca)
        /home/larsgard/go/src/github.com/nilsmagnus/grib/griblib/sections.go:51 +0xa9
main.main()
        /home/larsgard/go/src/github.com/nilsmagnus/grib2influx/main.go:47 +0x17a
done
```

**Comment by landru29** [comment]
Should be fixed with PR https://github.com/nilsmagnus/grib/pull/15
